name: TestRun
on:
  workflow_dispatch:
    inputs:
      groups:
        default: 'all'
        required: true
        type: string
  push:
    inputs:
      groups:
        default: 'all'
        required: false
    branches:
      - 'main'
      - 'feature-*'
  pull_request:
    inputs:
      default: 'all'
        required: false
    types:
      - opened
    branches:
      - 'main'
jobs:
  Runtests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Run tests
        env:
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: ./gradlew test -P groups=${{ inputs.groups }}
      - name: Upload report
        uses: actions/upload-artifact@v4
        with: 
          name: testng-report
          path: Reports/report.html
