name: TestRun
on:
  workflow_dispatch:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
      - 'feature_*'
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  Runtests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Run tests
        run: ./gradlew test
      - name: Upload report
        uses: actions/upload-artifact@v4
        with: 
          name: testng-report
          path: TestNG_Reports/index.html
      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: feature-allure
          allure_report: allure-report
          allure_history: allure-history
      - name: Add report to github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: feature-allure
          PUBLISH_DIR: allure-history
