name: TestRun
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'feature-*'
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  Runtests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Run tests
        run: ./gradlew test
  Report:
    needs: Runtests
    runs-on: ubuntu-latest
    steps:
      - name: Allure Report
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
            allure_results: target/allure-results
            gh_pages: reports
            allure_report: allure-report
            allure_history: allure-history
      - name: Add report to github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: reports
            PUBLISH_DIR: allure-history
