name: Automation test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Runtests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Run tests
        run: ./gradlew test
      - name: Create report
        uses: vs1300/AutomationTest@master
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: new check name
          report_paths: "**/index.html"
