name: TestRun
on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature_*'
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  Run tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Run tests
        run: ./gradlew test
      - name: Upload report
        uses: actions/upload-artifact@v4
        with: testng-report
          path: |
            TestNG_Reports/index.html
